packages:
  - name: functions
    shared: false
    functions:
      - name: scheduler
        environment:
          TWILIO_ACCOUNT_SID: "${TWILIO_ACCOUNT_SID}"
          TWILIO_AUTH_TOKEN: "${TWILIO_AUTH_TOKEN}"
          TWILIO_PHONE_NUMBER: "${TWILIO_PHONE_NUMBER}"
          PERSONAL_PHONE_NUMBER: "${PERSONAL_PHONE_NUMBER}"
        binary: false
        main: "main"
        runtime: nodejs:18
        web: false
        triggers:
          - name: trigger_magic_card
            sourceType: scheduler
            sourceDetails:
              cron: "0 8,12,16,20 * * *"
